trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

# Etapa de Build
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Instalar y compilar'
    steps:
      - checkout: self
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Instalar Node.js'
      - script: |
          npm install
          npm run build --if-present
        displayName: 'npm install & build'

              # DEBUG: ver d칩nde qued칩 tu carpeta de build
      - script: |
          echo ">>> Build.SourcesDirectory = $(Build.SourcesDirectory)"
          ls -R $(Build.SourcesDirectory)
        displayName: '游댌 Debug: listar carpetas y archivos'

      - task: ArchiveFiles@2
        displayName: 'Zip de assets est치ticos'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/build'
          includeRootFolder: false
          archiveType: zip
          archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
          replaceExistingArchive: true
      - publish: $(Build.ArtifactStagingDirectory)/release.zip
        artifact: drop

# Etapa de Deploy
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Desplegar con Azure CLI'
    steps:
      - download: current
        artifact: drop
      - task: AzureCLI@2
        displayName: 'Deploy est치tico con CLI'
        inputs:
          azureSubscription: 'SC-CasinoDemo'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az webapp deployment source config-zip \
              --resource-group MiResourceGroup \
              --name reactcasinodemo \
              --src $(Build.ArtifactStagingDirectory)/release.zip
