name: Cleanup old artifacts

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "7 days" # Delete artifacts older than 7 days
